Progress Assignement
Arrow98/React pull request #1
Opened 2024-11-14 17:04 UTC by Arrow98

2024-11-14 17:06 UTC, kobbyowen commented
Please do not use AI

2024-11-18 12:17 UTC, Arrow98 commented
![Screenshot 2024-11-18 121321](https://github.com/user-attachments/assets/6192ecb8-3b3f-4a97-80e5-55aab77f81f0)

2024-11-18 12:18 UTC, Arrow98 commented
![Screenshot 2024-11-18 121137](https://github.com/user-attachments/assets/3cb72908-1998-4762-b828-894ee191ef42)

2024-11-18 12:43 UTC, kobbyowen commented on fruit.html
> +<!DOCTYPE html>
Remove this file, I do not need it

2024-11-18 12:44 UTC, kobbyowen commented on script.js
> +  console.log(progressText.textContent)
Remove console.log

2024-11-18 12:44 UTC, kobbyowen commented on script.js
> +        task.topics.forEach(topicObj=>{
Function is too long, can we decompose it into smaller functions

2024-11-18 12:45 UTC, kobbyowen commented on script.js
> +    console.log(checked)
Remove console.log

2024-11-18 12:45 UTC, kobbyowen commented on script.js
> +    const ArrCheckBox = [...checkBox]
use camelCalse for variable names, why is it capitalised ?

2024-11-18 12:45 UTC, kobbyowen commented on script.js
> +    console.log(progressPercentage)
console.log

2024-11-18 12:46 UTC, kobbyowen commented on style.css
> +#progressText {
why are you mixing the class names naming conventions. You are using hyphenated classes, I suggest ou do same here for consistency 
`#progress-bar`

2024-11-18 12:48 UTC, kobbyowen requested changes
Added some reviews. Please address them

2025-02-11 16:50 UTC, kobbyowen approved these changes

2025-02-11 16:51 UTC, merged